### ISSUE TITLE
XML file

### ISSUE THREAD

**Issue by colejensen** [colejensen/finalproject#1]
When I upload my aligned genome file to BEAUTi, choose my XML file parameters, and generate the new XML file I get a weird problem. I do not get any kind of error during the generation process, but when I open the XML file in a text editor (to input my starting tree) I notice that when using an alignment file that large (2,000+ genomes) the file stops writing during the portion where each sequence is included. I can make XML files with smaller genomes amounts (around 1000 genomes) and have it include everything I need.

**Comment by caseywdunn** [comment]
I think that this is going to be far too many taxa for BEAST, regardless of this specific technical challenge. I suggest you use iqtree to build the tip dated trees - 

http://www.iqtree.org/doc/Dating#inferring-time-tree-with-tip-dates
